const programs = [
  { n: "01", title: "Muay Thai", text: "Precision striking, clinch control and elite conditioning.", meta: "ADULTS · ALL LEVELS" },
  { n: "02", title: "Brazilian Jiu-Jitsu", text: "Build composure, leverage and confidence on the ground.", meta: "GI + NO-GI" },
  { n: "03", title: "Youth Academy", text: "Discipline, coordination and real confidence for young athletes.", meta: "AGES 6–15" },
];
const schedule = [["06:00", "Muay Thai", "Coach Arjun"],["07:30", "BJJ Fundamentals", "Coach Kabir"],["17:00", "Youth Academy", "Coach Mira"],["19:00", "Combat Conditioning", "Coach Arjun"]];
export default function Home() { return <main>
  <nav className="nav"><a className="brand" href="#top"><span className="brand-mark">I</span><span>IRONCLAD<small>MARTIAL ARTS</small></span></a><div className="nav-links"><a href="#programs">Programs</a><a href="#about">Academy</a><a href="#schedule">Schedule</a></div><a className="nav-cta" href="#trial">Start training <span>↗</span></a></nav>
  <section className="hero" id="top"><img className="hero-image" src="https://images.unsplash.com/photo-1555597673-b21d5c935865?auto=format&fit=crop&w=2000&q=90" alt="Martial artist training inside a dark combat gym"/><div className="hero-shade"/><div className="hero-copy"><p className="eyebrow"><span/> Bhopal’s premium combat academy</p><h1>Built by<br/>discipline.</h1><div className="hero-bottom"><p>Train with purpose. Move with confidence.<br/>Become harder to break.</p><a className="circle-link" href="#programs">↓</a></div></div><p className="vertical-type">EST. 2018 · BHOPAL</p></section>
  <section className="manifesto" id="about"><p className="section-label">[ THE IRONCLAD METHOD ]</p><h2>We don’t train to look tough.<br/><em>We train to become capable.</em></h2><div className="stats"><div><strong>08+</strong><span>Years forging athletes</span></div><div><strong>600</strong><span>Active members</span></div><div><strong>32</strong><span>Competition medals</span></div><div><strong>4.9</strong><span>Member rating</span></div></div></section>
  <section className="programs" id="programs"><div className="section-head"><div><p className="section-label red">[ CHOOSE YOUR DISCIPLINE ]</p><h2>Programs that<br/>change you.</h2></div><p>Every class is coached with intent—structured technique, live practice and measurable progress.</p></div><div className="program-grid">{programs.map((p,i)=><article className="program-card" key={p.title}><div className={`program-photo photo-${i+1}`}><span>{p.n}</span></div><div className="program-body"><p>{p.meta}</p><h3>{p.title}</h3><div><span>{p.text}</span><b>↗</b></div></div></article>)}</div></section>
  <section className="coach"><div className="coach-image"><img src="https://images.unsplash.com/photo-1564415315949-7a0c4c73aab4?auto=format&fit=crop&w=1200&q=90" alt="Martial arts coach preparing for training"/></div><div className="coach-copy"><p className="section-label red">[ HEAD COACH ]</p><h2>Arjun<br/>Rathore.</h2><p className="quote">“Technique makes you dangerous. Discipline makes you dependable.”</p><p>National-level Muay Thai competitor, Brazilian Jiu-Jitsu brown belt and coach to more than 40 competitive athletes.</p><div className="credentials"><span>12 YEARS EXPERIENCE</span><span>WBC MUAY THAI CERTIFIED</span><span>BJJ BROWN BELT</span></div></div></section>
  <section className="schedule" id="schedule"><div><p className="section-label">[ TODAY AT IRONCLAD ]</p><h2>Show up.<br/>We’ll handle<br/>the rest.</h2></div><div className="schedule-list">{schedule.map(s=><div className="class-row" key={s[0]}><strong>{s[0]}</strong><span>{s[1]}<small>{s[2]}</small></span><b>60 MIN</b></div>)}</div></section>
  <section className="trial" id="trial"><p className="section-label">[ YOUR FIRST CLASS IS ON US ]</p><h2>Stop thinking.<br/><em>Start training.</em></h2><a href="https://wa.me/919999999999?text=Hi%20Ironclad%2C%20I%20want%20to%20book%20a%20free%20trial%20class" target="_blank" rel="noreferrer">Book your free trial <span>↗</span></a></section>
  <footer><a className="brand" href="#top"><span className="brand-mark">I</span><span>IRONCLAD<small>MARTIAL ARTS</small></span></a><p>TRAIN HARD · LIVE READY</p><div><a href="#programs">Instagram</a><a href="#schedule">Contact</a></div></footer>
</main> }
